version: '3'

services:
  backend-api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - 52197:5000
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    volumes:
      - ./site/nginx/spa.conf:/etc/nginx/conf.d/default.conf
      - ./site/public:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - backend-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
